apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: openshift-storage-classes-gitops

resources:
  - base

labels:
  - pairs:
      app.kubernetes.io/name: storage-classes
      app.kubernetes.io/managed-by: kustomize
      cluster.name: REPLACE_WITH_YOUR_CLUSTER_NAME

commonAnnotations:
  managed-by: gitops
  last-updated: "2025-08-20"
